<?php 
/*
Plugin Name: webp endpoint
Plugin URI: www.worzala.pl/wp/plugins/webp
Description: JPG-to-WEBP  https://localhost/wp-json/convert-image/jpg-to-webp/sago/3717b-1.webp
Version: 0.0.2
Author: Pawel Worzala
Author URI: www.worzala.pl
Text Domain: we
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}








//https://localhost/wp-json/convert-image/uri


function webp_get_endpoint_phrase($request) {

    //global $wp;
    //$url = home_url( add_query_arg( array(), $wp->request ) );

    //$url = str_replace('wp-json/convert-image/webp/', 'wp-content/uploads/', $url);

    $filenameWEBP = $_SERVER["DOCUMENT_ROOT"].'/app/uploads/'.$request->get_param('url');

    //var_dump($url);
    //exit;

    //$url = str_replace('https:', 'http:', $url);

    //$filenameWEBP = $url;
    $filenameJPG = str_replace('.webp','.jpg',$filenameWEBP);

    if(!file_exists($filename)){

        $data = file_get_contents($filenameJPG);

        $im = imagecreatefromstring($data);

        $webp = imagewebp($im, $filenameWEBP, 90);
        imagedestroy($im);

    }


    header("Content-Type: image/webp");

    echo file_get_contents($filenameWEBP);
    exit;
}

///wp-json/convert-image/webp/
function webp_register_example_routes() {
    
    register_rest_route( 'convert-image', '/webp/(?P<url>.*)', array(
        'methods'  => WP_REST_Server::READABLE,
        'callback' => 'webp_get_endpoint_phrase',
        'args' => [
             'url'
         ],
    ) );
}
 
add_action( 'rest_api_init', 'webp_register_example_routes' );








function replaceUrlToWebp($url){

    /*if(!is_string($url)){
        return $url;
    }

    if(!strpos($url,'.jpg')){
        return $url;
    }*/

    //https://sago-online.pl/app/uploads/2022/05/3865a-1-300x300.webp
    //https://sago-online.pl/app/uploads/2022/05/3865a-1-300x300.jpg

    $url = str_replace('app/uploads/','wp-json/convert-image/webp/',$url);
    $url = str_replace('wp-content/uploads/','wp-json/convert-image/webp/',$url);
    return str_replace('.jpg', '.webp', $url);

    return $url;
}

add_filter('wp_get_attachment_url', function($url) 
    {
        return replaceUrlToWebp($url);
    });
add_filter('wp_get_attachment_image_src', function($url) 
    {
        return replaceUrlToWebp($url);
    });

add_filter('wp_calculate_image_srcset', function($sources)
    {
    foreach($sources as $source) 
    {            
        $source['url'] = replaceUrlToWebp($source['url']);                      
    }       
    return $sources;
    });