<?php 
/*
Plugin Name: webp endpoint
Plugin URI: http://narloch.eu/wordpress/plugins/webp-endpoint
Description: JPG-to-WEBP
Version: 0.1.1
Author: Narloch.eu - Strony internetowe dla firm
Author URI: http://narloch.eu/
Text Domain: we
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}








//https://localhost/wp-json/convert-image/uri


function webp_get_endpoint_phrase($request) {

    //global $wp;
    //$url = home_url( add_query_arg( array(), $wp->request ) );

    //$url = str_replace('wp-json/convert-image/webp/', 'wp-content/uploads/', $url);

    $url=urldecode($request->get_param('url'));

    $filenameWEBP = $_SERVER["DOCUMENT_ROOT"].'/app/uploads/'.$url;
    $filenameJPG = str_replace('.webp','.jpg',$filenameWEBP);

    if(!file_exists($filenameJPG)){
        $filenameWEBP = $_SERVER["DOCUMENT_ROOT"].'/wp-content/uploads/'.$url;
        $filenameJPG = str_replace('.webp','.jpg',$filenameWEBP);
    }

    //var_dump($url);
    //exit;

    //$url = str_replace('https:', 'http:', $url);

    //$filenameWEBP = $url;
    

    if(!file_exists($filename)){

        $data = file_get_contents($filenameJPG);

        $im = imagecreatefromstring($data);

        $webp = imagewebp($im, $filenameWEBP, 90);
        imagedestroy($im);

    }


    $seconds_to_cache = 3600*24*365;
    $ts = gmdate("D, d M Y H:i:s", time() + $seconds_to_cache) . " GMT";
    header("Expires: $ts");
    header("Pragma: cache");
    header("Cache-Control: max-age=$seconds_to_cache");


    header("Content-Type: image/webp");

    echo file_get_contents($filenameWEBP);
    exit;
}

///wp-json/convert-image/webp/
function webp_register_example_routes() {
    
    register_rest_route( 'images', '/webp/(?P<url>.*)', array(
        'methods'  => WP_REST_Server::READABLE,
        'callback' => 'webp_get_endpoint_phrase',
        'args' => [
             'url'
         ],
    ) );
}
 
add_action( 'rest_api_init', 'webp_register_example_routes' );








function replaceUrlToWebp($url){

    /*if(is_array($url)&&(!is_string($url))){
        return $url;
    }*/

    //if(!is_array($url)&&strpos($url,'.jpg')){
        //return $url;
    //}

    //https://sago-online.pl/app/uploads/2022/05/3865a-1-300x300.webp
    //https://sago-online.pl/app/uploads/2022/05/3865a-1-300x300.jpg

    

    //$webps = str_replace('.jpg','.webp',$url);
    

    $urls=$url;
    if(is_array($urls)){
        $newUrls=[];
        foreach($urls as $url){
            //$url='https://sago-online.pl/app/uploads/2020/03/hala2.jpg';
            $webp = str_replace('.jpg','.webp',$url);
            $webp = str_replace('https://sago-online.pl/app/','../',$webp);
            //$webp = str_replace('https:','http:',$webp);
            //$dir=dirname(__FILE__."../");
            if(file_exists($webp)){
                //$webp = str_replace('http:','https:',$webp);
                $newUrls[]=$webp;
            }else{
                $newUrls[]=$url;
            }
        }
        $urls=$newUrls;
    }else{
        //$url='https://sago-online.pl/app/uploads/2020/03/hala2.jpg';
        $webp = str_replace('.jpg','.webp',$url);
        $webp = str_replace('https://sago-online.pl/app/','../',$webp);
        if(file_exists($webp)){
            $urls=$webp;
        }
    }
    //return str_replace('.jpg', '.webp', $url);

    return $urls;
    //}
    //return $url;
}

add_filter('wp_get_attachment_url', function($url) 
    {
        return replaceUrlToWebp($url);
    });
add_filter('wp_get_attachment_image_src', function($url) 
    {
        return replaceUrlToWebp($url);
    });

add_filter('wp_calculate_image_srcset', function($sources)
    {
    foreach($sources as $source) 
    {            
        $source['url'] = replaceUrlToWebp($source['url']);                      
    }       
    return $sources;
    });